<a href="https://colab.research.google.com/github/rajatkb/Intuition-Net_Physics-based-Image-segmentation-outpainting/blob/master/unet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np 
import os
import skimage.io as io
import skimage.transform as trans
import numpy as np
import keras as K
from keras.models import *
from keras.layers import *
from keras.optimizers import *
from keras.callbacks import ModelCheckpoint, LearningRateScheduler
from keras import backend as keras



import matplotlib.pyplot as plt
import cv2

from tqdm import tqdm
from PIL import Image


Using TensorFlow backend.


In [0]:
!wget https://www.dropbox.com/s/pxcz2wdz04zxocq/CamVid.zip?dl=1 -O CamVid.zip
!unzip CamVid.zip

--2019-03-27 16:51:09--  https://www.dropbox.com/s/pxcz2wdz04zxocq/CamVid.zip?dl=1
Resolving www.dropbox.com (www.dropbox.com)... 162.125.9.1, 2620:100:601f:1::a27d:901
Connecting to www.dropbox.com (www.dropbox.com)|162.125.9.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/dl/pxcz2wdz04zxocq/CamVid.zip [following]
--2019-03-27 16:51:09--  https://www.dropbox.com/s/dl/pxcz2wdz04zxocq/CamVid.zip
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc55c33fe2773d0ea0f096464faa.dl.dropboxusercontent.com/cd/0/get/Ad7SYoFy3gm3rwMVhtgyFh4SCA_ZsgcmyihIaAPMoITISvRFaim6HsRSnFFZFpODQ-5ZIiVnXf2tMba7uoA7HLiuZJrslIbegLbpRCaBvZRYgw/file?dl=1# [following]
--2019-03-27 16:51:09--  https://uc55c33fe2773d0ea0f096464faa.dl.dropboxusercontent.com/cd/0/get/Ad7SYoFy3gm3rwMVhtgyFh4SCA_ZsgcmyihIaAPMoITISvRFaim6HsRSnFFZFpODQ-5ZIiVnXf2tMba7uoA7HLiuZJrslIbegLbpRCaBvZRYgw/file?dl=1
Resolving uc55c33f

In [0]:
def binarylab(labels):
  x = np.zeros([992,320,12])
  for i in range(992):
    for j in range(320):
      x[i,j,labels[i][j]]=1
  return x

def loader(training_path, segmented_path, batch_size, h=320, w=992):
    filenames_t = os.listdir(training_path)
    total_files_t = len(filenames_t)
    
    filenames_s = os.listdir(segmented_path)
    total_files_s = len(filenames_s)
    
    assert(total_files_t == total_files_s)
    
    if str(batch_size).lower() == 'all':
        batch_size = total_files_s
    
    idx = 0
    while(1):
      # Choosing random indexes of images and labels
        batch_idxs = np.random.randint(0, total_files_s, batch_size)
            
        
        inputs = []
        labels = []
        count=0
        for jj in batch_idxs:
          # Reading normalized photo
            img = plt.imread(training_path + filenames_t[jj])
          # Resizing using nearest neighbor method
            img = cv2.resize(img, (h, w), cv2.INTER_NEAREST)
            inputs.append(img)
          
          # Reading semantic image
            img = Image.open(segmented_path + filenames_s[jj])
            img = np.array(img)
          # Resizing using nearest neighbor method
            img = cv2.resize(img, (h, w), cv2.INTER_NEAREST)
            labels.append(binarylab(img))
            
        
        
        inputs = np.stack(inputs, axis=2)
        
        yield inputs, np.array(labels)




In [0]:
def get_class_weights(num_classes, c=1.02):
    pipe = loader('/content/train/', '/content/trainannot/', batch_size='all')
    _, labels = next(pipe)
    all_labels = labels.flatten()
    each_class = np.bincount(all_labels, minlength=num_classes)
    prospensity_score = each_class / len(all_labels)
    class_weights = 1 / (np.log(c + prospensity_score))
    return class_weights
  
class_weighting= [0.2595, 0.1826, 4.5640, 0.1417, 0.9051, 0.3826, 9.6446, 1.8418, 6.6823, 6.2478, 3.0, 7.3614]

In [0]:
def get_crop_shape(target, refer):
        # width, the 3rd dimension
        cw = (target.get_shape()[2] - refer.get_shape()[2]).value
        assert (cw >= 0)
        if cw % 2 != 0:
            cw1, cw2 = int(cw/2), int(cw/2) + 1
        else:
            cw1, cw2 = int(cw/2), int(cw/2)
        # height, the 2nd dimension
        ch = (target.get_shape()[1] - refer.get_shape()[1]).value
        assert (ch >= 0)
        if ch % 2 != 0:
            ch1, ch2 = int(ch/2), int(ch/2) + 1
        else:
            ch1, ch2 = int(ch/2), int(ch/2)

        return (ch1, ch2), (cw1, cw2)

def unet(input_size = (320,992,3)):
  concat_axis = 3
  inputs = Input(input_size)
  conv1 = Conv2D(32, (3, 3), padding="same", name="conv1_1", activation="relu", data_format="channels_last")(inputs)
  conv1 = Conv2D(32, (3, 3), padding="same", activation="relu", data_format="channels_last")(conv1)
  pool1 = MaxPooling2D(pool_size=(2, 2), data_format="channels_last")(conv1)
  conv2 = Conv2D(64, (3, 3), padding="same", activation="relu", data_format="channels_last")(pool1)
  conv2 = Conv2D(64, (3, 3), padding="same", activation="relu", data_format="channels_last")(conv2)
  pool2 = MaxPooling2D(pool_size=(2, 2), data_format="channels_last")(conv2)

  conv3 = Conv2D(128, (3, 3), padding="same", activation="relu", data_format="channels_last")(pool2)
  conv3 = Conv2D(128, (3, 3), padding="same", activation="relu", data_format="channels_last")(conv3)
  pool3 = MaxPooling2D(pool_size=(2, 2), data_format="channels_last")(conv3)

  conv4 = Conv2D(256, (3, 3), padding="same", activation="relu", data_format="channels_last")(pool3)
  conv4 = Conv2D(256, (3, 3), padding="same", activation="relu", data_format="channels_last")(conv4)
  pool4 = MaxPooling2D(pool_size=(2, 2), data_format="channels_last")(conv4)

  conv5 = Conv2D(512, (3, 3), padding="same", activation="relu", data_format="channels_last")(pool4)
  conv5 = Conv2D(512, (3, 3), padding="same", activation="relu", data_format="channels_last")(conv5)

  up_conv5 = UpSampling2D(size=(2, 2), data_format="channels_last")(conv5)
  ch, cw = get_crop_shape(conv4, up_conv5)
  crop_conv4 = Cropping2D(cropping=(ch,cw), data_format="channels_last")(conv4)
  up6   = concatenate([up_conv5, crop_conv4], axis=concat_axis)
  conv6 = Conv2D(256, (3, 3), padding="same", activation="relu", data_format="channels_last")(up6)
  conv6 = Conv2D(256, (3, 3), padding="same", activation="relu", data_format="channels_last")(conv6)

  up_conv6 = UpSampling2D(size=(2, 2), data_format="channels_last")(conv6)
  ch, cw = get_crop_shape(conv3, up_conv6)
  crop_conv3 = Cropping2D(cropping=(ch,cw), data_format="channels_last")(conv3)
  up7   = concatenate([up_conv6, crop_conv3], axis=concat_axis)
  conv7 = Conv2D(128, (3, 3), padding="same", activation="relu", data_format="channels_last")(up7)
  conv7 = Conv2D(128, (3, 3), padding="same", activation="relu", data_format="channels_last")(conv7)

  up_conv7 = UpSampling2D(size=(2, 2), data_format="channels_last")(conv7)
  ch, cw = get_crop_shape(conv2, up_conv7)
  crop_conv2 = Cropping2D(cropping=(ch,cw), data_format="channels_last")(conv2)
  up8   = concatenate([up_conv7, crop_conv2], axis=concat_axis)
  conv8 = Conv2D(64, (3, 3), padding="same", activation="relu", data_format="channels_last")(up8)
  conv8 = Conv2D(64, (3, 3), padding="same", activation="relu", data_format="channels_last")(conv8)

  up_conv8 = UpSampling2D(size=(2, 2), data_format="channels_last")(conv8)
  ch, cw = get_crop_shape(conv1, up_conv8)
  crop_conv1 = Cropping2D(cropping=(ch,cw), data_format="channels_last")(conv1)
  up9   = concatenate([up_conv8, crop_conv1], axis=concat_axis)
  conv9 = Conv2D(32, (3, 3), padding="same", activation="relu", data_format="channels_last")(up9)
  conv9 = Conv2D(32, (3, 3), padding="same", activation="relu", data_format="channels_last")(conv9)

  #ch, cw = get_crop_shape(inputs, conv9)
  #conv9  = ZeroPadding2D(padding=(ch[0],cw[0]), data_format="channels_last")(conv9)
  #conv10 = Conv2D(1, (1, 1), data_format="channels_last", activation="sigmoid")(conv9)

  conv10 = Conv2D(12, 1, activation = 'softmax')(conv9)
  model = Model(input = inputs, output = conv10)

  model.compile(optimizer = Adam(lr = 1e-4), loss = 'categorical_crossentropy', metrics = ['accuracy'])

  model.summary()

  
  return model


In [0]:
lr = 5e-4
batch_size = 10


print_every = 5
eval_every = 5

In [0]:
train_losses = []
eval_losses = []

bc_train = 367 // batch_size # mini_batch train
bc_eval = 101 // batch_size  # mini_batch validation

# Define pipeline objects
pipe = loader('/content/train/', '/content/trainannot/', batch_size)
eval_pipe = loader('/content/val/', '/content/valannot/', batch_size)

epochs = 100

# Train loop
model=unet(input_size = (320,992,3))
for e in range(1, epochs+1):
    
    print ('-'*15,'Epoch %d' % e, '-'*15)
    
    for _ in tqdm(range(bc_train)):
        X_batch, mask_batch = next(pipe)
        X_batch=np.einsum('klij->ilkj', X_batch)
        mask_batch= np.einsum('klij->kilj',mask_batch)

        print(np.array((mask_batch).shape))
        history = model.fit(X_batch, mask_batch, batch_size=10, nb_epoch=100,verbose=1, class_weight=class_weighting)
        
        model.save_weights('model_weight_ep100.hdf5')
      
               

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:73: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=Tensor("co...)`
  0%|          | 0/36 [00:00<?, ?it/s]

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            (None, 320, 992, 3)  0                                            
__________________________________________________________________________________________________
conv1_1 (Conv2D)                (None, 320, 992, 32) 896         input_2[0][0]                    
__________________________________________________________________________________________________
conv2d_19 (Conv2D)              (None, 320, 992, 32) 9248        conv1_1[0][0]                    
__________________________________________________________________________________________________
max_pooling2d_5 (MaxPooling2D)  (None, 160, 496, 32) 0           conv2d_19[0][0]                  
__________________________________________________________________________________________________
conv2d_20 

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:25: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
Epoch 1/100
10/10 [==============================] - 20s 2s/step - loss: 2.5006 - acc: 0.0129
Epoch 2/100
10/10 [==============================] - 3s 281ms/step - loss: 2.4925 - acc: 0.0143
Epoch 3/100
10/10 [==============================] - 3s 271ms/step - loss: 2.4856 - acc: 0.0270
Epoch 4/100
10/10 [==============================] - 3s 271ms/step - loss: 2.4795 - acc: 0.0650
Epoch 5/100
10/10 [==============================] - 3s 271ms/step - loss: 2.4736 - acc: 0.1026
Epoch 6/100
10/10 [==============================] - 3s 269ms/step - loss: 2.4679 - acc: 0.1128
Epoch 7/100
10/10 [==============================] - 3s 270ms/step - loss: 2.4622 - acc: 0.1148
Epoch 8/100
10/10 [==============================] - 3s 270ms/step - loss: 2.4571 - acc: 0.1155
Epoch 9/100
10/10 [==============================] - 3s 270ms/step - loss: 2.4517 - acc: 0.1156
Epoch 10/100
10/10 [==============================] - 3s 271

  3%|▎         | 1/36 [04:56<2:52:54, 296.41s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 289ms/step - loss: 1.5173 - acc: 0.5599
Epoch 2/100
10/10 [==============================] - 3s 277ms/step - loss: 1.5095 - acc: 0.5770
Epoch 3/100
10/10 [==============================] - 3s 274ms/step - loss: 1.4450 - acc: 0.5798
Epoch 4/100
10/10 [==============================] - 3s 276ms/step - loss: 1.4727 - acc: 0.5612
Epoch 5/100
10/10 [==============================] - 3s 274ms/step - loss: 1.4709 - acc: 0.4390
Epoch 6/100
10/10 [==============================] - 3s 275ms/step - loss: 1.3980 - acc: 0.5026
Epoch 7/100
10/10 [==============================] - 3s 275ms/step - loss: 1.3971 - acc: 0.5730
Epoch 8/100
10/10 [==============================] - 3s 274ms/step - loss: 1.3531 - acc: 0.5734
Epoch 9/100
10/10 [==============================] - 3s 275ms/step - loss: 1.3596 - acc: 0.5686
Epoch 10/100
10/10 [==============================] - 3s 274ms/step - loss: 1.3388 - acc: 0.5670
Epoch 11/100
10/10 [=

  6%|▌         | 2/36 [09:34<2:44:46, 290.78s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 288ms/step - loss: 1.3955 - acc: 0.5823
Epoch 2/100
10/10 [==============================] - 3s 276ms/step - loss: 1.4902 - acc: 0.5281
Epoch 3/100
10/10 [==============================] - 3s 276ms/step - loss: 1.3623 - acc: 0.5564
Epoch 4/100
10/10 [==============================] - 3s 276ms/step - loss: 1.3398 - acc: 0.5566
Epoch 5/100
10/10 [==============================] - 3s 277ms/step - loss: 1.3890 - acc: 0.5615
Epoch 6/100
10/10 [==============================] - 3s 277ms/step - loss: 1.1872 - acc: 0.6326
Epoch 7/100
10/10 [==============================] - 3s 275ms/step - loss: 1.1770 - acc: 0.6381
Epoch 8/100
10/10 [==============================] - 3s 278ms/step - loss: 1.2799 - acc: 0.6164
Epoch 9/100
10/10 [==============================] - 3s 276ms/step - loss: 1.2094 - acc: 0.6380
Epoch 10/100
10/10 [==============================] - 3s 274ms/step - loss: 1.1129 - acc: 0.6578
Epoch 11/100
10/10 [=

  8%|▊         | 3/36 [14:12<2:37:54, 287.10s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 283ms/step - loss: 0.9700 - acc: 0.7230
Epoch 2/100
10/10 [==============================] - 3s 275ms/step - loss: 0.9603 - acc: 0.7055
Epoch 3/100
10/10 [==============================] - 3s 272ms/step - loss: 0.9891 - acc: 0.6804
Epoch 4/100
10/10 [==============================] - 3s 273ms/step - loss: 0.9038 - acc: 0.7203
Epoch 5/100
10/10 [==============================] - 3s 273ms/step - loss: 0.8710 - acc: 0.7348
Epoch 6/100
10/10 [==============================] - 3s 275ms/step - loss: 0.8881 - acc: 0.7240
Epoch 7/100
10/10 [==============================] - 3s 275ms/step - loss: 0.8605 - acc: 0.7284
Epoch 8/100
10/10 [==============================] - 3s 275ms/step - loss: 0.8583 - acc: 0.7337
Epoch 9/100
10/10 [==============================] - 3s 276ms/step - loss: 0.8475 - acc: 0.7418
Epoch 10/100
10/10 [==============================] - 3s 276ms/step - loss: 0.8502 - acc: 0.7409
Epoch 11/100
10/10 [=

 11%|█         | 4/36 [18:50<2:31:39, 284.37s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 276ms/step - loss: 1.0567 - acc: 0.6676
Epoch 2/100
10/10 [==============================] - 3s 273ms/step - loss: 1.0337 - acc: 0.6753
Epoch 3/100
10/10 [==============================] - 3s 273ms/step - loss: 1.0111 - acc: 0.6853
Epoch 4/100
10/10 [==============================] - 3s 273ms/step - loss: 0.9859 - acc: 0.6951
Epoch 5/100
10/10 [==============================] - 3s 275ms/step - loss: 0.9684 - acc: 0.7055
Epoch 6/100
10/10 [==============================] - 3s 272ms/step - loss: 0.9618 - acc: 0.7067
Epoch 7/100
10/10 [==============================] - 3s 272ms/step - loss: 0.9464 - acc: 0.7121
Epoch 8/100
10/10 [==============================] - 3s 274ms/step - loss: 0.9387 - acc: 0.7131
Epoch 9/100
10/10 [==============================] - 3s 276ms/step - loss: 0.9291 - acc: 0.7147
Epoch 10/100
10/10 [==============================] - 3s 275ms/step - loss: 0.9182 - acc: 0.7160
Epoch 11/100
10/10 [=

 14%|█▍        | 5/36 [23:28<2:25:55, 282.44s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 283ms/step - loss: 0.9117 - acc: 0.7161
Epoch 2/100
10/10 [==============================] - 3s 276ms/step - loss: 0.9508 - acc: 0.7141
Epoch 3/100
10/10 [==============================] - 3s 275ms/step - loss: 0.9885 - acc: 0.6994
Epoch 4/100
10/10 [==============================] - 3s 277ms/step - loss: 1.0184 - acc: 0.7020
Epoch 5/100
10/10 [==============================] - 3s 276ms/step - loss: 0.9628 - acc: 0.7099
Epoch 6/100
10/10 [==============================] - 3s 274ms/step - loss: 0.9485 - acc: 0.7269
Epoch 7/100
10/10 [==============================] - 3s 275ms/step - loss: 0.9285 - acc: 0.7246
Epoch 8/100
10/10 [==============================] - 3s 276ms/step - loss: 0.9375 - acc: 0.7276
Epoch 9/100
10/10 [==============================] - 3s 274ms/step - loss: 0.8418 - acc: 0.7519
Epoch 10/100
10/10 [==============================] - 3s 277ms/step - loss: 0.8316 - acc: 0.7588
Epoch 11/100
10/10 [=

 17%|█▋        | 6/36 [28:07<2:20:39, 281.31s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 284ms/step - loss: 0.9613 - acc: 0.7388
Epoch 2/100
10/10 [==============================] - 3s 276ms/step - loss: 1.2502 - acc: 0.7471
Epoch 3/100
10/10 [==============================] - 3s 276ms/step - loss: 1.1297 - acc: 0.6479
Epoch 4/100
10/10 [==============================] - 3s 276ms/step - loss: 1.1147 - acc: 0.6781
Epoch 5/100
10/10 [==============================] - 3s 277ms/step - loss: 0.8164 - acc: 0.7615
Epoch 6/100
10/10 [==============================] - 3s 275ms/step - loss: 0.8428 - acc: 0.7685
Epoch 7/100
10/10 [==============================] - 3s 278ms/step - loss: 0.9060 - acc: 0.7520
Epoch 8/100
10/10 [==============================] - 3s 281ms/step - loss: 0.8401 - acc: 0.7614
Epoch 9/100
10/10 [==============================] - 3s 276ms/step - loss: 0.8216 - acc: 0.7596
Epoch 10/100
10/10 [==============================] - 3s 276ms/step - loss: 0.7862 - acc: 0.7673
Epoch 11/100
10/10 [=

 19%|█▉        | 7/36 [32:46<2:15:36, 280.58s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 279ms/step - loss: 1.0106 - acc: 0.7374
Epoch 2/100
10/10 [==============================] - 3s 277ms/step - loss: 0.9764 - acc: 0.7161
Epoch 3/100
10/10 [==============================] - 3s 277ms/step - loss: 1.0082 - acc: 0.7136
Epoch 4/100
10/10 [==============================] - 3s 274ms/step - loss: 0.9561 - acc: 0.7245
Epoch 5/100
10/10 [==============================] - 3s 277ms/step - loss: 0.8987 - acc: 0.7282
Epoch 6/100
10/10 [==============================] - 3s 276ms/step - loss: 0.9046 - acc: 0.7314
Epoch 7/100
10/10 [==============================] - 3s 277ms/step - loss: 0.9115 - acc: 0.7284
Epoch 8/100
10/10 [==============================] - 3s 277ms/step - loss: 0.7562 - acc: 0.7676
Epoch 9/100
10/10 [==============================] - 3s 278ms/step - loss: 0.7683 - acc: 0.7704
Epoch 10/100
10/10 [==============================] - 3s 275ms/step - loss: 0.7740 - acc: 0.7664
Epoch 11/100
10/10 [=

 22%|██▏       | 8/36 [37:24<2:10:39, 279.97s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 277ms/step - loss: 0.9120 - acc: 0.7549
Epoch 2/100
10/10 [==============================] - 3s 277ms/step - loss: 0.8099 - acc: 0.7648
Epoch 3/100
10/10 [==============================] - 3s 276ms/step - loss: 0.8099 - acc: 0.7603
Epoch 4/100
10/10 [==============================] - 3s 275ms/step - loss: 0.8011 - acc: 0.7595
Epoch 5/100
10/10 [==============================] - 3s 278ms/step - loss: 0.7811 - acc: 0.7600
Epoch 6/100
10/10 [==============================] - 3s 276ms/step - loss: 0.7393 - acc: 0.7785
Epoch 7/100
10/10 [==============================] - 3s 276ms/step - loss: 0.7165 - acc: 0.7861
Epoch 8/100
10/10 [==============================] - 3s 276ms/step - loss: 0.7116 - acc: 0.7898
Epoch 9/100
10/10 [==============================] - 3s 275ms/step - loss: 0.7218 - acc: 0.7836
Epoch 10/100
10/10 [==============================] - 3s 276ms/step - loss: 0.6701 - acc: 0.8015
Epoch 11/100
10/10 [=

 25%|██▌       | 9/36 [42:03<2:05:50, 279.66s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 278ms/step - loss: 0.8420 - acc: 0.7784
Epoch 2/100
10/10 [==============================] - 3s 276ms/step - loss: 0.8162 - acc: 0.7855
Epoch 3/100
10/10 [==============================] - 3s 279ms/step - loss: 0.7976 - acc: 0.7782
Epoch 4/100
10/10 [==============================] - 3s 280ms/step - loss: 0.7075 - acc: 0.8027
Epoch 5/100
10/10 [==============================] - 3s 278ms/step - loss: 0.7090 - acc: 0.8005
Epoch 6/100
10/10 [==============================] - 3s 277ms/step - loss: 0.6701 - acc: 0.8129
Epoch 7/100
10/10 [==============================] - 3s 278ms/step - loss: 0.6548 - acc: 0.8154
Epoch 8/100
10/10 [==============================] - 3s 276ms/step - loss: 0.6165 - acc: 0.8249
Epoch 9/100
10/10 [==============================] - 3s 274ms/step - loss: 0.6139 - acc: 0.8262
Epoch 10/100
10/10 [==============================] - 3s 277ms/step - loss: 0.5898 - acc: 0.8318
Epoch 11/100
10/10 [=

 28%|██▊       | 10/36 [46:41<2:00:58, 279.18s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 283ms/step - loss: 0.6934 - acc: 0.8112
Epoch 2/100
10/10 [==============================] - 3s 276ms/step - loss: 0.6414 - acc: 0.8139
Epoch 3/100
10/10 [==============================] - 3s 276ms/step - loss: 0.6050 - acc: 0.8255
Epoch 4/100
10/10 [==============================] - 3s 277ms/step - loss: 0.5818 - acc: 0.8354
Epoch 5/100
10/10 [==============================] - 3s 276ms/step - loss: 0.5739 - acc: 0.8402
Epoch 6/100
10/10 [==============================] - 3s 275ms/step - loss: 0.5580 - acc: 0.8481
Epoch 7/100
10/10 [==============================] - 3s 275ms/step - loss: 0.5423 - acc: 0.8497
Epoch 8/100
10/10 [==============================] - 3s 278ms/step - loss: 0.5357 - acc: 0.8511
Epoch 9/100
10/10 [==============================] - 3s 275ms/step - loss: 0.5155 - acc: 0.8573
Epoch 10/100
10/10 [==============================] - 3s 274ms/step - loss: 0.5122 - acc: 0.8595
Epoch 11/100
10/10 [=

 31%|███       | 11/36 [51:19<1:56:10, 278.80s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 279ms/step - loss: 0.9393 - acc: 0.7505
Epoch 2/100
10/10 [==============================] - 3s 276ms/step - loss: 0.8419 - acc: 0.7612
Epoch 3/100
10/10 [==============================] - 3s 276ms/step - loss: 0.7463 - acc: 0.7818
Epoch 4/100
10/10 [==============================] - 3s 277ms/step - loss: 0.7339 - acc: 0.7858
Epoch 5/100
10/10 [==============================] - 3s 277ms/step - loss: 0.7373 - acc: 0.7814
Epoch 6/100
10/10 [==============================] - 3s 275ms/step - loss: 0.7145 - acc: 0.7878
Epoch 7/100
10/10 [==============================] - 3s 275ms/step - loss: 0.6941 - acc: 0.7924
Epoch 8/100
10/10 [==============================] - 3s 276ms/step - loss: 0.6656 - acc: 0.8000
Epoch 9/100
10/10 [==============================] - 3s 275ms/step - loss: 0.6514 - acc: 0.8009
Epoch 10/100
10/10 [==============================] - 3s 275ms/step - loss: 0.6250 - acc: 0.8097
Epoch 11/100
10/10 [=

 33%|███▎      | 12/36 [55:57<1:51:27, 278.65s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 286ms/step - loss: 0.9389 - acc: 0.7838
Epoch 2/100
10/10 [==============================] - 3s 276ms/step - loss: 0.7310 - acc: 0.8003
Epoch 3/100
10/10 [==============================] - 3s 276ms/step - loss: 0.6731 - acc: 0.8043
Epoch 4/100
10/10 [==============================] - 3s 276ms/step - loss: 0.6453 - acc: 0.8093
Epoch 5/100
10/10 [==============================] - 3s 277ms/step - loss: 0.6131 - acc: 0.8269
Epoch 6/100
10/10 [==============================] - 3s 278ms/step - loss: 0.5791 - acc: 0.8345
Epoch 7/100
10/10 [==============================] - 3s 280ms/step - loss: 0.5618 - acc: 0.8389
Epoch 8/100
10/10 [==============================] - 3s 279ms/step - loss: 0.5425 - acc: 0.8451
Epoch 9/100
10/10 [==============================] - 3s 276ms/step - loss: 0.5376 - acc: 0.8477
Epoch 10/100
10/10 [==============================] - 3s 275ms/step - loss: 0.5202 - acc: 0.8532
Epoch 11/100
10/10 [=

 36%|███▌      | 13/36 [1:00:36<1:46:49, 278.66s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 288ms/step - loss: 0.6547 - acc: 0.8145
Epoch 2/100
10/10 [==============================] - 3s 276ms/step - loss: 0.5992 - acc: 0.8334
Epoch 3/100
10/10 [==============================] - 3s 277ms/step - loss: 0.5772 - acc: 0.8382
Epoch 4/100
10/10 [==============================] - 3s 277ms/step - loss: 0.5528 - acc: 0.8427
Epoch 5/100
10/10 [==============================] - 3s 276ms/step - loss: 0.5392 - acc: 0.8499
Epoch 6/100
10/10 [==============================] - 3s 273ms/step - loss: 0.5275 - acc: 0.8571
Epoch 7/100
10/10 [==============================] - 3s 273ms/step - loss: 0.5089 - acc: 0.8622
Epoch 8/100
10/10 [==============================] - 3s 273ms/step - loss: 0.5029 - acc: 0.8620
Epoch 9/100
10/10 [==============================] - 3s 279ms/step - loss: 0.5042 - acc: 0.8601
Epoch 10/100
10/10 [==============================] - 3s 276ms/step - loss: 0.4820 - acc: 0.8692
Epoch 11/100
10/10 [=

 39%|███▉      | 14/36 [1:05:14<1:42:09, 278.60s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 277ms/step - loss: 0.8305 - acc: 0.8020
Epoch 2/100
10/10 [==============================] - 3s 277ms/step - loss: 0.8738 - acc: 0.7665
Epoch 3/100
10/10 [==============================] - 3s 275ms/step - loss: 0.9772 - acc: 0.7554
Epoch 4/100
10/10 [==============================] - 3s 277ms/step - loss: 0.6659 - acc: 0.8124
Epoch 5/100
10/10 [==============================] - 3s 277ms/step - loss: 0.9744 - acc: 0.7212
Epoch 6/100
10/10 [==============================] - 3s 275ms/step - loss: 0.7717 - acc: 0.7777
Epoch 7/100
10/10 [==============================] - 3s 278ms/step - loss: 0.9491 - acc: 0.7346
Epoch 8/100
10/10 [==============================] - 3s 277ms/step - loss: 0.8087 - acc: 0.7609
Epoch 9/100
10/10 [==============================] - 3s 276ms/step - loss: 0.6889 - acc: 0.8035
Epoch 10/100
10/10 [==============================] - 3s 275ms/step - loss: 0.7393 - acc: 0.8003
Epoch 11/100
10/10 [=

 42%|████▏     | 15/36 [1:09:53<1:37:28, 278.51s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 278ms/step - loss: 0.8381 - acc: 0.8078
Epoch 2/100
10/10 [==============================] - 3s 276ms/step - loss: 0.7061 - acc: 0.8217
Epoch 3/100
10/10 [==============================] - 3s 275ms/step - loss: 0.6494 - acc: 0.8162
Epoch 4/100
10/10 [==============================] - 3s 276ms/step - loss: 0.5750 - acc: 0.8405
Epoch 5/100
10/10 [==============================] - 3s 279ms/step - loss: 0.5636 - acc: 0.8445
Epoch 6/100
10/10 [==============================] - 3s 276ms/step - loss: 0.5455 - acc: 0.8488
Epoch 7/100
10/10 [==============================] - 3s 276ms/step - loss: 0.5429 - acc: 0.8483
Epoch 8/100
10/10 [==============================] - 3s 275ms/step - loss: 0.5100 - acc: 0.8591
Epoch 9/100
10/10 [==============================] - 3s 276ms/step - loss: 0.4971 - acc: 0.8638
Epoch 10/100
10/10 [==============================] - 3s 276ms/step - loss: 0.4898 - acc: 0.8649
Epoch 11/100
10/10 [=

 44%|████▍     | 16/36 [1:14:31<1:32:51, 278.57s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 288ms/step - loss: 1.1235 - acc: 0.7572
Epoch 2/100
10/10 [==============================] - 3s 276ms/step - loss: 0.9429 - acc: 0.7602
Epoch 3/100
10/10 [==============================] - 3s 277ms/step - loss: 0.8379 - acc: 0.7665
Epoch 4/100
10/10 [==============================] - 3s 279ms/step - loss: 0.8194 - acc: 0.7685
Epoch 5/100
10/10 [==============================] - 3s 275ms/step - loss: 0.7930 - acc: 0.7786
Epoch 6/100
10/10 [==============================] - 3s 276ms/step - loss: 0.7793 - acc: 0.7859
Epoch 7/100
10/10 [==============================] - 3s 277ms/step - loss: 0.7303 - acc: 0.7983
Epoch 8/100
10/10 [==============================] - 3s 278ms/step - loss: 0.7203 - acc: 0.7984
Epoch 9/100
10/10 [==============================] - 3s 278ms/step - loss: 0.6940 - acc: 0.8077
Epoch 10/100
10/10 [==============================] - 3s 276ms/step - loss: 0.6868 - acc: 0.8079
Epoch 11/100
10/10 [=

 47%|████▋     | 17/36 [1:19:11<1:28:16, 278.74s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 285ms/step - loss: 0.9371 - acc: 0.7600
Epoch 2/100
10/10 [==============================] - 3s 276ms/step - loss: 1.2598 - acc: 0.7422
Epoch 3/100
10/10 [==============================] - 3s 278ms/step - loss: 0.7717 - acc: 0.7959
Epoch 4/100
10/10 [==============================] - 3s 276ms/step - loss: 0.8826 - acc: 0.7553
Epoch 5/100
10/10 [==============================] - 3s 276ms/step - loss: 1.3660 - acc: 0.6580
Epoch 6/100
10/10 [==============================] - 3s 275ms/step - loss: 2.4231 - acc: 0.1763
Epoch 7/100
10/10 [==============================] - 3s 282ms/step - loss: 1.8906 - acc: 0.2765
Epoch 8/100
10/10 [==============================] - 3s 275ms/step - loss: 2.0021 - acc: 0.2773
Epoch 9/100
10/10 [==============================] - 3s 274ms/step - loss: 1.9528 - acc: 0.3065
Epoch 10/100
10/10 [==============================] - 3s 276ms/step - loss: 1.8278 - acc: 0.3786
Epoch 11/100
10/10 [=

 50%|█████     | 18/36 [1:23:48<1:23:30, 278.39s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 277ms/step - loss: 1.1056 - acc: 0.6732
Epoch 2/100
10/10 [==============================] - 3s 276ms/step - loss: 1.0524 - acc: 0.6636
Epoch 3/100
10/10 [==============================] - 3s 274ms/step - loss: 1.0616 - acc: 0.6589
Epoch 4/100
10/10 [==============================] - 3s 275ms/step - loss: 1.0207 - acc: 0.6715
Epoch 5/100
10/10 [==============================] - 3s 275ms/step - loss: 0.9895 - acc: 0.6709
Epoch 6/100
10/10 [==============================] - 3s 275ms/step - loss: 1.0164 - acc: 0.6633
Epoch 7/100
10/10 [==============================] - 3s 275ms/step - loss: 1.0028 - acc: 0.6711
Epoch 8/100
10/10 [==============================] - 3s 278ms/step - loss: 1.0023 - acc: 0.6740
Epoch 9/100
10/10 [==============================] - 3s 279ms/step - loss: 0.9825 - acc: 0.6889
Epoch 10/100
10/10 [==============================] - 3s 274ms/step - loss: 0.9760 - acc: 0.6919
Epoch 11/100
10/10 [=

 53%|█████▎    | 19/36 [1:28:26<1:18:51, 278.32s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 277ms/step - loss: 0.9771 - acc: 0.7113
Epoch 2/100
10/10 [==============================] - 3s 278ms/step - loss: 0.9198 - acc: 0.7070
Epoch 3/100
10/10 [==============================] - 3s 275ms/step - loss: 0.8930 - acc: 0.6949
Epoch 4/100
10/10 [==============================] - 3s 275ms/step - loss: 0.8591 - acc: 0.7066
Epoch 5/100
10/10 [==============================] - 3s 275ms/step - loss: 0.8208 - acc: 0.7370
Epoch 6/100
10/10 [==============================] - 3s 273ms/step - loss: 0.8218 - acc: 0.7356
Epoch 7/100
10/10 [==============================] - 3s 274ms/step - loss: 0.8106 - acc: 0.7369
Epoch 8/100
10/10 [==============================] - 3s 273ms/step - loss: 0.7970 - acc: 0.7411
Epoch 9/100
10/10 [==============================] - 3s 275ms/step - loss: 0.7951 - acc: 0.7399
Epoch 10/100
10/10 [==============================] - 3s 275ms/step - loss: 0.7863 - acc: 0.7463
Epoch 11/100
10/10 [=

 56%|█████▌    | 20/36 [1:33:04<1:14:09, 278.12s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 274ms/step - loss: 1.7920 - acc: 0.5927
Epoch 2/100
10/10 [==============================] - 3s 278ms/step - loss: 1.5968 - acc: 0.5254
Epoch 3/100
10/10 [==============================] - 3s 275ms/step - loss: 1.3555 - acc: 0.6287
Epoch 4/100
10/10 [==============================] - 3s 275ms/step - loss: 1.3986 - acc: 0.6073
Epoch 5/100
10/10 [==============================] - 3s 277ms/step - loss: 1.2333 - acc: 0.6204
Epoch 6/100
10/10 [==============================] - 3s 277ms/step - loss: 1.3973 - acc: 0.5428
Epoch 7/100
10/10 [==============================] - 3s 273ms/step - loss: 1.1543 - acc: 0.6647
Epoch 8/100
10/10 [==============================] - 3s 273ms/step - loss: 1.0328 - acc: 0.7050
Epoch 9/100
10/10 [==============================] - 3s 275ms/step - loss: 1.1147 - acc: 0.6638
Epoch 10/100
10/10 [==============================] - 3s 277ms/step - loss: 1.0559 - acc: 0.6682
Epoch 11/100
10/10 [=

 58%|█████▊    | 21/36 [1:37:42<1:09:31, 278.07s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 289ms/step - loss: 1.1362 - acc: 0.7018
Epoch 2/100
10/10 [==============================] - 3s 274ms/step - loss: 1.2028 - acc: 0.6343
Epoch 3/100
10/10 [==============================] - 3s 276ms/step - loss: 1.1811 - acc: 0.6223
Epoch 4/100
10/10 [==============================] - 3s 275ms/step - loss: 1.1598 - acc: 0.6187
Epoch 5/100
10/10 [==============================] - 3s 276ms/step - loss: 1.0196 - acc: 0.6705
Epoch 6/100
10/10 [==============================] - 3s 275ms/step - loss: 0.9736 - acc: 0.6973
Epoch 7/100
10/10 [==============================] - 3s 275ms/step - loss: 0.9536 - acc: 0.7095
Epoch 8/100
10/10 [==============================] - 3s 275ms/step - loss: 0.9715 - acc: 0.6968
Epoch 9/100
10/10 [==============================] - 3s 277ms/step - loss: 0.9112 - acc: 0.7121
Epoch 10/100
10/10 [==============================] - 3s 277ms/step - loss: 0.8756 - acc: 0.7291
Epoch 11/100
10/10 [=

 61%|██████    | 22/36 [1:42:20<1:04:51, 277.96s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 276ms/step - loss: 1.1104 - acc: 0.6875
Epoch 2/100
10/10 [==============================] - 3s 277ms/step - loss: 1.0523 - acc: 0.7287
Epoch 3/100
10/10 [==============================] - 3s 278ms/step - loss: 1.0061 - acc: 0.7257
Epoch 4/100
10/10 [==============================] - 3s 275ms/step - loss: 0.8860 - acc: 0.7371
Epoch 5/100
10/10 [==============================] - 3s 276ms/step - loss: 0.9410 - acc: 0.7153
Epoch 6/100
10/10 [==============================] - 3s 275ms/step - loss: 0.9015 - acc: 0.7335
Epoch 7/100
10/10 [==============================] - 3s 277ms/step - loss: 0.8369 - acc: 0.7538
Epoch 8/100
10/10 [==============================] - 3s 277ms/step - loss: 0.7885 - acc: 0.7658
Epoch 9/100
10/10 [==============================] - 3s 275ms/step - loss: 0.8133 - acc: 0.7535
Epoch 10/100
10/10 [==============================] - 3s 276ms/step - loss: 0.7787 - acc: 0.7688
Epoch 11/100
10/10 [=

 64%|██████▍   | 23/36 [1:46:57<1:00:12, 277.88s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 278ms/step - loss: 0.8898 - acc: 0.7748
Epoch 2/100
10/10 [==============================] - 3s 274ms/step - loss: 0.8541 - acc: 0.7583
Epoch 3/100
10/10 [==============================] - 3s 275ms/step - loss: 0.7714 - acc: 0.7861
Epoch 4/100
10/10 [==============================] - 3s 276ms/step - loss: 0.7710 - acc: 0.7927
Epoch 5/100
10/10 [==============================] - 3s 275ms/step - loss: 0.7349 - acc: 0.7866
Epoch 6/100
10/10 [==============================] - 3s 276ms/step - loss: 0.6970 - acc: 0.8008
Epoch 7/100
10/10 [==============================] - 3s 276ms/step - loss: 0.6919 - acc: 0.8009
Epoch 8/100
10/10 [==============================] - 3s 275ms/step - loss: 0.6609 - acc: 0.8094
Epoch 9/100
10/10 [==============================] - 3s 277ms/step - loss: 0.6410 - acc: 0.8195
Epoch 10/100
10/10 [==============================] - 3s 274ms/step - loss: 0.6413 - acc: 0.8180
Epoch 11/100
10/10 [=

 67%|██████▋   | 24/36 [1:51:35<55:34, 277.89s/it]  

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 283ms/step - loss: 1.0115 - acc: 0.7363
Epoch 2/100
10/10 [==============================] - 3s 277ms/step - loss: 1.0071 - acc: 0.7071
Epoch 3/100
10/10 [==============================] - 3s 276ms/step - loss: 0.8831 - acc: 0.7373
Epoch 4/100
10/10 [==============================] - 3s 275ms/step - loss: 1.0205 - acc: 0.7157
Epoch 5/100
10/10 [==============================] - 3s 276ms/step - loss: 0.8711 - acc: 0.7326
Epoch 6/100
10/10 [==============================] - 3s 275ms/step - loss: 0.9093 - acc: 0.7314
Epoch 7/100
10/10 [==============================] - 3s 277ms/step - loss: 0.7554 - acc: 0.7769
Epoch 8/100
10/10 [==============================] - 3s 274ms/step - loss: 0.7650 - acc: 0.7697
Epoch 9/100
10/10 [==============================] - 3s 276ms/step - loss: 0.7328 - acc: 0.7807
Epoch 10/100
10/10 [==============================] - 3s 277ms/step - loss: 0.7037 - acc: 0.7912
Epoch 11/100
10/10 [=

 69%|██████▉   | 25/36 [1:56:13<50:56, 277.83s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 282ms/step - loss: 1.4951 - acc: 0.6938
Epoch 2/100
10/10 [==============================] - 3s 274ms/step - loss: 2.6448 - acc: 0.4314
Epoch 3/100
10/10 [==============================] - 3s 274ms/step - loss: 1.7223 - acc: 0.6921
Epoch 4/100
10/10 [==============================] - 3s 274ms/step - loss: 1.6601 - acc: 0.6510
Epoch 5/100
10/10 [==============================] - 3s 275ms/step - loss: 1.2723 - acc: 0.6562
Epoch 6/100
10/10 [==============================] - 3s 274ms/step - loss: 1.1761 - acc: 0.6776
Epoch 7/100
10/10 [==============================] - 3s 275ms/step - loss: 1.3138 - acc: 0.6285
Epoch 8/100
10/10 [==============================] - 3s 277ms/step - loss: 1.2020 - acc: 0.6746
Epoch 9/100
10/10 [==============================] - 3s 273ms/step - loss: 1.3460 - acc: 0.6080
Epoch 10/100
10/10 [==============================] - 3s 274ms/step - loss: 1.2728 - acc: 0.6256
Epoch 11/100
10/10 [=

 72%|███████▏  | 26/36 [2:00:50<46:16, 277.67s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 279ms/step - loss: 0.8801 - acc: 0.7491
Epoch 2/100
10/10 [==============================] - 3s 277ms/step - loss: 0.8707 - acc: 0.7220
Epoch 3/100
10/10 [==============================] - 3s 274ms/step - loss: 0.8145 - acc: 0.7538
Epoch 4/100
10/10 [==============================] - 3s 273ms/step - loss: 0.7775 - acc: 0.7583
Epoch 5/100
10/10 [==============================] - 3s 272ms/step - loss: 0.7624 - acc: 0.7683
Epoch 6/100
10/10 [==============================] - 3s 274ms/step - loss: 0.7456 - acc: 0.7824
Epoch 7/100
10/10 [==============================] - 3s 274ms/step - loss: 0.7187 - acc: 0.7880
Epoch 8/100
10/10 [==============================] - 3s 274ms/step - loss: 0.7004 - acc: 0.7917
Epoch 9/100
10/10 [==============================] - 3s 279ms/step - loss: 0.6978 - acc: 0.7920
Epoch 10/100
10/10 [==============================] - 3s 274ms/step - loss: 0.6736 - acc: 0.8007
Epoch 11/100
10/10 [=

 75%|███████▌  | 27/36 [2:05:28<41:38, 277.56s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 286ms/step - loss: 0.9805 - acc: 0.7446
Epoch 2/100
10/10 [==============================] - 3s 272ms/step - loss: 0.8827 - acc: 0.7444
Epoch 3/100
10/10 [==============================] - 3s 280ms/step - loss: 0.8376 - acc: 0.7620
Epoch 4/100
10/10 [==============================] - 3s 275ms/step - loss: 0.8103 - acc: 0.7638
Epoch 5/100
10/10 [==============================] - 3s 275ms/step - loss: 0.7780 - acc: 0.7604
Epoch 6/100
10/10 [==============================] - 3s 273ms/step - loss: 0.7364 - acc: 0.7688
Epoch 7/100
10/10 [==============================] - 3s 276ms/step - loss: 0.7230 - acc: 0.7781
Epoch 8/100
10/10 [==============================] - 3s 275ms/step - loss: 0.6723 - acc: 0.7929
Epoch 9/100
10/10 [==============================] - 3s 275ms/step - loss: 0.6448 - acc: 0.8037
Epoch 10/100
10/10 [==============================] - 3s 277ms/step - loss: 0.6491 - acc: 0.8041
Epoch 11/100
10/10 [=

 78%|███████▊  | 28/36 [2:10:05<37:00, 277.57s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 275ms/step - loss: 1.3343 - acc: 0.6593
Epoch 2/100
10/10 [==============================] - 3s 277ms/step - loss: 1.0206 - acc: 0.7020
Epoch 3/100
10/10 [==============================] - 3s 274ms/step - loss: 1.1166 - acc: 0.6757
Epoch 4/100
10/10 [==============================] - 3s 277ms/step - loss: 1.0055 - acc: 0.6931
Epoch 5/100
10/10 [==============================] - 3s 278ms/step - loss: 0.8483 - acc: 0.7486
Epoch 6/100
10/10 [==============================] - 3s 275ms/step - loss: 0.8808 - acc: 0.7313
Epoch 7/100
10/10 [==============================] - 3s 275ms/step - loss: 0.8611 - acc: 0.7413
Epoch 8/100
10/10 [==============================] - 3s 277ms/step - loss: 0.7543 - acc: 0.7652
Epoch 9/100
10/10 [==============================] - 3s 275ms/step - loss: 0.7419 - acc: 0.7779
Epoch 10/100
10/10 [==============================] - 3s 275ms/step - loss: 0.7531 - acc: 0.7678
Epoch 11/100
10/10 [=

 81%|████████  | 29/36 [2:14:43<32:22, 277.55s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 284ms/step - loss: 0.9436 - acc: 0.7736
Epoch 2/100
10/10 [==============================] - 3s 274ms/step - loss: 0.7948 - acc: 0.7863
Epoch 3/100
10/10 [==============================] - 3s 275ms/step - loss: 0.7081 - acc: 0.8001
Epoch 4/100
10/10 [==============================] - 3s 275ms/step - loss: 0.7045 - acc: 0.7876
Epoch 5/100
10/10 [==============================] - 3s 275ms/step - loss: 0.6606 - acc: 0.7990
Epoch 6/100
10/10 [==============================] - 3s 273ms/step - loss: 0.6316 - acc: 0.8093
Epoch 7/100
10/10 [==============================] - 3s 280ms/step - loss: 0.5862 - acc: 0.8290
Epoch 8/100
10/10 [==============================] - 3s 275ms/step - loss: 0.5877 - acc: 0.8308
Epoch 9/100
10/10 [==============================] - 3s 277ms/step - loss: 0.5718 - acc: 0.8357
Epoch 10/100
10/10 [==============================] - 3s 275ms/step - loss: 0.5541 - acc: 0.8400
Epoch 11/100
10/10 [=

 83%|████████▎ | 30/36 [2:19:21<27:46, 277.68s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 275ms/step - loss: 0.8505 - acc: 0.7907
Epoch 2/100
10/10 [==============================] - 3s 274ms/step - loss: 0.8420 - acc: 0.7755
Epoch 3/100
10/10 [==============================] - 3s 276ms/step - loss: 0.7503 - acc: 0.7998
Epoch 4/100
10/10 [==============================] - 3s 275ms/step - loss: 0.6942 - acc: 0.8042
Epoch 5/100
10/10 [==============================] - 3s 276ms/step - loss: 0.6437 - acc: 0.8098
Epoch 6/100
10/10 [==============================] - 3s 276ms/step - loss: 0.6210 - acc: 0.8180
Epoch 7/100
10/10 [==============================] - 3s 275ms/step - loss: 0.5956 - acc: 0.8248
Epoch 8/100
10/10 [==============================] - 3s 278ms/step - loss: 0.5755 - acc: 0.8327
Epoch 9/100
10/10 [==============================] - 3s 275ms/step - loss: 0.5805 - acc: 0.8303
Epoch 10/100
10/10 [==============================] - 3s 274ms/step - loss: 0.5364 - acc: 0.8453
Epoch 11/100
10/10 [=

 86%|████████▌ | 31/36 [2:23:58<23:08, 277.67s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 279ms/step - loss: 0.6852 - acc: 0.8203
Epoch 2/100
10/10 [==============================] - 3s 277ms/step - loss: 0.6515 - acc: 0.8162
Epoch 3/100
10/10 [==============================] - 3s 275ms/step - loss: 0.6775 - acc: 0.8171
Epoch 4/100
10/10 [==============================] - 3s 276ms/step - loss: 0.6227 - acc: 0.8167
Epoch 5/100
10/10 [==============================] - 3s 274ms/step - loss: 0.5470 - acc: 0.8431
Epoch 6/100
10/10 [==============================] - 3s 275ms/step - loss: 0.5582 - acc: 0.8379
Epoch 7/100
10/10 [==============================] - 3s 276ms/step - loss: 0.5082 - acc: 0.8545
Epoch 8/100
10/10 [==============================] - 3s 276ms/step - loss: 0.5234 - acc: 0.8462
Epoch 9/100
10/10 [==============================] - 3s 275ms/step - loss: 0.4888 - acc: 0.8601
Epoch 10/100
10/10 [==============================] - 3s 278ms/step - loss: 0.5001 - acc: 0.8560
Epoch 11/100
10/10 [=

 89%|████████▉ | 32/36 [2:28:36<18:30, 277.74s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 283ms/step - loss: 0.7438 - acc: 0.8064
Epoch 2/100
10/10 [==============================] - 3s 277ms/step - loss: 0.6666 - acc: 0.8271
Epoch 3/100
10/10 [==============================] - 3s 274ms/step - loss: 0.6244 - acc: 0.8295
Epoch 4/100
10/10 [==============================] - 3s 274ms/step - loss: 0.5923 - acc: 0.8318
Epoch 5/100
10/10 [==============================] - 3s 274ms/step - loss: 0.5538 - acc: 0.8450
Epoch 6/100
10/10 [==============================] - 3s 277ms/step - loss: 0.5319 - acc: 0.8452
Epoch 7/100
10/10 [==============================] - 3s 273ms/step - loss: 0.5236 - acc: 0.8466
Epoch 8/100
10/10 [==============================] - 3s 272ms/step - loss: 0.4921 - acc: 0.8579
Epoch 9/100
10/10 [==============================] - 3s 274ms/step - loss: 0.4815 - acc: 0.8602
Epoch 10/100
10/10 [==============================] - 3s 278ms/step - loss: 0.4797 - acc: 0.8615
Epoch 11/100
10/10 [=

 92%|█████████▏| 33/36 [2:33:14<13:53, 277.74s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 276ms/step - loss: 0.6799 - acc: 0.8205
Epoch 2/100
10/10 [==============================] - 3s 273ms/step - loss: 0.6467 - acc: 0.8190
Epoch 3/100
10/10 [==============================] - 3s 275ms/step - loss: 0.5679 - acc: 0.8397
Epoch 4/100
10/10 [==============================] - 3s 275ms/step - loss: 0.5734 - acc: 0.8350
Epoch 5/100
10/10 [==============================] - 3s 275ms/step - loss: 0.5416 - acc: 0.8412
Epoch 6/100
10/10 [==============================] - 3s 275ms/step - loss: 0.5321 - acc: 0.8471
Epoch 7/100
10/10 [==============================] - 3s 278ms/step - loss: 0.5043 - acc: 0.8544
Epoch 8/100
10/10 [==============================] - 3s 274ms/step - loss: 0.5021 - acc: 0.8535
Epoch 9/100
10/10 [==============================] - 3s 275ms/step - loss: 0.4760 - acc: 0.8614
Epoch 10/100
10/10 [==============================] - 3s 275ms/step - loss: 0.4769 - acc: 0.8602
Epoch 11/100
10/10 [=

 94%|█████████▍| 34/36 [2:37:51<09:15, 277.63s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 275ms/step - loss: 0.7162 - acc: 0.8149
Epoch 2/100
10/10 [==============================] - 3s 278ms/step - loss: 0.7319 - acc: 0.8251
Epoch 3/100
10/10 [==============================] - 3s 274ms/step - loss: 0.7641 - acc: 0.7790
Epoch 4/100
10/10 [==============================] - 3s 279ms/step - loss: 0.5444 - acc: 0.8467
Epoch 5/100
10/10 [==============================] - 3s 276ms/step - loss: 0.6229 - acc: 0.8375
Epoch 6/100
10/10 [==============================] - 3s 279ms/step - loss: 0.5102 - acc: 0.8556
Epoch 7/100
10/10 [==============================] - 3s 276ms/step - loss: 0.5397 - acc: 0.8422
Epoch 8/100
10/10 [==============================] - 3s 277ms/step - loss: 0.4965 - acc: 0.8578
Epoch 9/100
10/10 [==============================] - 3s 276ms/step - loss: 0.4879 - acc: 0.8604
Epoch 10/100
10/10 [==============================] - 3s 276ms/step - loss: 0.4738 - acc: 0.8627
Epoch 11/100
10/10 [=

 97%|█████████▋| 35/36 [2:42:30<04:37, 277.91s/it]

[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 281ms/step - loss: 0.7613 - acc: 0.8131
Epoch 2/100
10/10 [==============================] - 3s 275ms/step - loss: 0.8495 - acc: 0.7678
Epoch 3/100
10/10 [==============================] - 3s 277ms/step - loss: 0.9905 - acc: 0.7679
Epoch 4/100
10/10 [==============================] - 3s 275ms/step - loss: 0.8998 - acc: 0.7533
Epoch 5/100
10/10 [==============================] - 3s 275ms/step - loss: 0.7396 - acc: 0.7788
Epoch 6/100
10/10 [==============================] - 3s 276ms/step - loss: 0.8769 - acc: 0.7309
Epoch 7/100
10/10 [==============================] - 3s 275ms/step - loss: 0.6465 - acc: 0.8169
Epoch 8/100
10/10 [==============================] - 3s 275ms/step - loss: 0.5879 - acc: 0.8198
Epoch 9/100
10/10 [==============================] - 3s 275ms/step - loss: 0.6973 - acc: 0.7884
Epoch 10/100
10/10 [==============================] - 3s 275ms/step - loss: 0.5976 - acc: 0.8154
Epoch 11/100
10/10 [=

  0%|          | 0/36 [00:00<?, ?it/s]

--------------- Epoch 2 ---------------
[ 10 320 992  12]
Epoch 1/100
10/10 [==============================] - 3s 275ms/step - loss: 0.7283 - acc: 0.8169
Epoch 2/100
10/10 [==============================] - 3s 276ms/step - loss: 0.7202 - acc: 0.8166
Epoch 3/100
10/10 [==============================] - 3s 278ms/step - loss: 0.5974 - acc: 0.8349
Epoch 4/100
10/10 [==============================] - 3s 275ms/step - loss: 0.5373 - acc: 0.8427
Epoch 5/100
10/10 [==============================] - 3s 276ms/step - loss: 0.5267 - acc: 0.8480
Epoch 6/100
10/10 [==============================] - 3s 276ms/step - loss: 0.4821 - acc: 0.8642
Epoch 7/100
10/10 [==============================] - 3s 275ms/step - loss: 0.4761 - acc: 0.8639
Epoch 8/100
10/10 [==============================] - 3s 276ms/step - loss: 0.4378 - acc: 0.8754
Epoch 9/100
10/10 [==============================] - 3s 277ms/step - loss: 0.4583 - acc: 0.8694
Epoch 10/100
10/10 [==============================] - 3s 275ms/step - loss: 0.

KeyboardInterrupt: ignored